sensitiveCodepaths:
   - 'README.md'
allowedAuthors:
  usernames:
    # GitHub username
    # - john-doe
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
  # - '@john-doe'
