sensitiveCodepaths:
  # Files only allowed authors can modify
  - 'README.md'
  # - 'app.js'
  # - 'controllers/**/*.js'
allowedAuthors:
  usernames:
    # GitHub username
    # - john-doe
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
  # - '@john-doe'
